<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Delete from library</name>
   <tag></tag>
   <elementGuidId>bf150970-258b-46d2-8af5-2891bc553756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='portals']/div/div[2]/div/div/ul/li[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.select-category__button.select-category__button_remove</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2e7a73a0-18c0-4ff2-9663-7ad36a5e4999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-category__button select-category__button_remove</value>
      <webElementGuid>a75cc5bc-2723-4ab0-ac8a-aeec0bf9fbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac8c0b15-2212-48f8-8bd2-bf9a656561cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4c75c51c-166b-40d3-aaf3-5ba08c1ec29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete from library</value>
      <webElementGuid>79a88cc9-0f3a-4f2e-a85f-d81f1c1850c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portals&quot;)/div[1]/div[@class=&quot;dropdown__container dropdown__container_opened dropdown__container_standard-widths dropdown__container_card game-card-buttons__dropdown-wrapper&quot;]/div[@class=&quot;dropdown__content&quot;]/div[@class=&quot;btn-add-game__categories&quot;]/ul[@class=&quot;select-category&quot;]/li[@class=&quot;select-category__item&quot;]/div[@class=&quot;select-category__button select-category__button_remove&quot;]</value>
      <webElementGuid>087f05b1-faf8-4eb7-9ac5-20d4c866513e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portals']/div/div[2]/div/div/ul/li[6]/div</value>
      <webElementGuid>85236c03-76d7-48a5-ac96-98ebe1ee2a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('I', &quot;'&quot;, 'll play it later')])[1]/following::div[1]</value>
      <webElementGuid>e74e3d08-d817-4df3-b754-fdb5ae9832d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not played'])[1]/following::div[1]</value>
      <webElementGuid>de0cc42c-b0b6-440a-84bd-f2ecc85ddf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies Policy'])[1]/preceding::div[1]</value>
      <webElementGuid>4e81765d-5856-4552-a4eb-d2986cde9445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Witcher 3: Wild Hunt'])[1]/preceding::div[12]</value>
      <webElementGuid>e46ca0d9-ce3b-43ff-9993-70fd395af275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Delete from library']/parent::*</value>
      <webElementGuid>491e20f6-54a4-4b3c-84a7-4a1630eab981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div</value>
      <webElementGuid>c14dab34-acc1-45a3-9441-62bac886ac37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Delete from library' or . = 'Delete from library')]</value>
      <webElementGuid>248365e4-c772-4710-86de-78fc65203eff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
