<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Added to</name>
   <tag></tag>
   <elementGuidId>616d2291-ac2c-480c-95dc-0753913028de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div/main/div/div[2]/div/div[3]/div[4]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-wishlist__subtitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>76119e23-5dfb-4da4-bd64-acbabd0d44ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-wishlist__subtitle</value>
      <webElementGuid>461dc3ff-feb5-4759-bd0a-9d9a310aa945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Added to</value>
      <webElementGuid>5b060772-8215-4f75-a41a-5d4d49b19c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app locale-en&quot;]/div[@class=&quot;page game&quot;]/div[@class=&quot;page__content-wrap-centerer&quot;]/div[@class=&quot;page__content-wrap with-sidebar&quot;]/main[@class=&quot;page__content&quot;]/div[@class=&quot;game__content-wrap&quot;]/div[@class=&quot;game-content-columns&quot;]/div[1]/div[@class=&quot;game-buttons-new game__buttons&quot;]/div[@class=&quot;btn-wishlist btn-wishlist_active&quot;]/div[@class=&quot;btn-wishlist__text&quot;]/div[@class=&quot;btn-wishlist__subtitle&quot;]</value>
      <webElementGuid>84ee6457-7bbc-470a-96ec-a11e3082c7f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/main/div/div[2]/div/div[3]/div[4]/div/div</value>
      <webElementGuid>80c22494-3d2b-437c-b78d-29bfbe82fed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My games'])[1]/following::div[5]</value>
      <webElementGuid>27e9deba-ed22-4814-b70a-3a54a6e3a712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Added to'])[1]/following::div[6]</value>
      <webElementGuid>bc026b36-a8c1-42be-88aa-689926dd5edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save to'])[1]/preceding::div[5]</value>
      <webElementGuid>9a8d8908-f9c2-44dd-83fc-7eba62e8e0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div[4]/div/div</value>
      <webElementGuid>c5104320-c4bb-41a2-b1b8-85067a0cfb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Added to' or . = 'Added to')]</value>
      <webElementGuid>620226c7-fbef-4963-bae5-c204901ccdb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
