<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Exceptional4519</name>
   <tag></tag>
   <elementGuidId>f53fda40-6a30-4f11-aca6-70bcc9db33d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div/main/div/div[2]/div/div[5]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.rating-distribution__label.rating-distribution__label_active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ecea0c30-481c-4e7a-961d-7a1c857634a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rating-distribution__label rating-distribution__label_active</value>
      <webElementGuid>bae16084-0ea8-4ae0-9170-4ab85d600c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a59733e7-22ec-48e7-8ebd-a9a3ad13d2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>82ab6c24-54eb-436e-8e0d-ed6cde3017d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Exceptional4519</value>
      <webElementGuid>18737c3d-4ddf-43ba-87dd-d718508fca05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app locale-en&quot;]/div[@class=&quot;page game&quot;]/div[@class=&quot;page__content-wrap-centerer&quot;]/div[@class=&quot;page__content-wrap with-sidebar&quot;]/main[@class=&quot;page__content&quot;]/div[@class=&quot;game__content-wrap&quot;]/div[@class=&quot;game-content-columns&quot;]/div[1]/div[@class=&quot;rating-distribution game-rating-distribution&quot;]/div[@class=&quot;rating-distribution__meta&quot;]/div[@class=&quot;rating-distribution__labels&quot;]/div[@class=&quot;rating-distribution__label rating-distribution__label_active&quot;]</value>
      <webElementGuid>261a961b-913f-499e-8190-b5634a47ee26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/main/div/div[2]/div/div[5]/div[2]/div/div</value>
      <webElementGuid>28125d3f-b6a9-48e5-b608-b6dc4892ca7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top 2015'])[1]/following::div[13]</value>
      <webElementGuid>6715d40b-7a0f-4307-8829-10cbabe9a584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[2]/following::div[14]</value>
      <webElementGuid>7ec7591f-874e-4132-ac0f-93bae6bd783f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recommended'])[1]/preceding::div[6]</value>
      <webElementGuid>85e419f0-9cd6-4cc7-a0dd-ad73cc6f5f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div</value>
      <webElementGuid>0f4adf2c-a051-41d9-a4fe-13bba11a69dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Exceptional4519' or . = 'Exceptional4519')]</value>
      <webElementGuid>d9ec17ec-9441-4de8-b72f-d42cff50170f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
