<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RPG_btn-collection__icon btn-collection_a73910</name>
   <tag></tag>
   <elementGuidId>5563b3f2-5837-438d-8e63-413ad85b7922</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div/main/div/div[2]/div/div[3]/div[6]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-collection__icon.btn-collection__icon-added</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7477664-a794-446d-bf89-ded6705522a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-collection__icon btn-collection__icon-added</value>
      <webElementGuid>84955ccb-1ae7-4901-91a5-0665932a7dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app locale-en&quot;]/div[@class=&quot;page game&quot;]/div[@class=&quot;page__content-wrap-centerer&quot;]/div[@class=&quot;page__content-wrap with-sidebar&quot;]/main[@class=&quot;page__content&quot;]/div[@class=&quot;game__content-wrap&quot;]/div[@class=&quot;game-content-columns&quot;]/div[1]/div[@class=&quot;game-buttons-new game__buttons&quot;]/div[@class=&quot;btn-collection btn-collection_active&quot;]/div[@class=&quot;btn-collection__icon btn-collection__icon-added&quot;]</value>
      <webElementGuid>1b196c31-f06d-417a-a9ec-69db40469add</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/main/div/div[2]/div/div[3]/div[6]/div[2]</value>
      <webElementGuid>dec7de5f-537d-474a-a0ee-0db44a2530d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]</value>
      <webElementGuid>c6227d9b-40bf-4352-a710-a0c22464afa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
