<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_RPG</name>
   <tag></tag>
   <elementGuidId>4fc18a14-f20f-4c9c-b466-f81ac2fc0b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='portals']/div/div[2]/div/ul/li/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select-content__item__main__desktop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee2a5c67-fb2c-4d99-bbb5-abe94fb12ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-content__item__main__desktop</value>
      <webElementGuid>e6799799-f837-4905-803c-8991258f12b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00a91965-5cb8-4123-824c-ebb1b9dfb0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b74c09e-420e-469b-acc7-b4492b3e2174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RPG</value>
      <webElementGuid>38b34b0f-ee26-4e51-9717-a890e21e8761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portals&quot;)/div[1]/div[@class=&quot;dropdown__container dropdown__container_opened dropdown__container_standard-widths dropdown__container_card game-card-buttons__dropdown-wrapper&quot;]/div[@class=&quot;dropdown__content&quot;]/ul[@class=&quot;select-content game__collections-list&quot;]/li[@class=&quot;select-content__item select-content__item_active&quot;]/div[@class=&quot;select-content__item__main&quot;]/span[@class=&quot;select-content__item__main__desktop&quot;]</value>
      <webElementGuid>d380843e-a80f-4368-8aba-60140d5a19c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portals']/div/div[2]/div/ul/li/div/span</value>
      <webElementGuid>e58fef36-0773-4e23-b953-2eecdb090d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start a new collection'])[1]/following::span[1]</value>
      <webElementGuid>42c124c1-3524-44cb-94d5-fff44e8540c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select collections'])[1]/following::span[1]</value>
      <webElementGuid>aa3cb946-85ac-4ae4-add2-d5199349864c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RPG'])[2]/preceding::span[1]</value>
      <webElementGuid>088380a4-1d8b-42ee-b7f2-93e0d94edd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies Policy'])[1]/preceding::span[2]</value>
      <webElementGuid>e98427ee-56d2-4072-b25b-62b693aeab8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RPG']/parent::*</value>
      <webElementGuid>da51f08e-ee5e-4aed-99d5-92574d8d7c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>bcb30662-5215-4aaf-abd0-94a6e0aaa310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'RPG' or . = 'RPG')]</value>
      <webElementGuid>1e317751-2ea8-4e7b-9cf1-4ea0249340d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
