<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign upThis password is not safe. Pleas_447561</name>
   <tag></tag>
   <elementGuidId>ff751cfc-86c0-4d9f-8b8e-a46cea65f337</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.page__content-wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b96cb32f-3083-49ae-b233-af6908e13006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page__content-wrap</value>
      <webElementGuid>32dddcf8-31ac-4309-acac-dedb3f77cef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign upThis password is not safe. Please, create another.min. 8 characters, can't match email or username, can't be numericSign upAlready have an account? Log in.You can use social accounts to sign upContinue with FacebookContinue with TwitterContinue with SteamBy signing up, you agree to RAWG’s Terms of Service and Privacy Policy.</value>
      <webElementGuid>7ce79821-2548-4b3c-a114-764aeec85541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app locale-en&quot;]/div[@class=&quot;page page_secondary&quot;]/div[@class=&quot;page__content-wrap-centerer&quot;]/div[@class=&quot;page__content-wrap&quot;]</value>
      <webElementGuid>2e331c5d-9141-45e5-ae40-9cda9c2ace07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div</value>
      <webElementGuid>93556b6d-9118-456f-ba64-5596c7121f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sitemap'])[1]/following::div[2]</value>
      <webElementGuid>31780e22-78e5-4239-9d2f-4115334049da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get an API key'])[1]/following::div[2]</value>
      <webElementGuid>07434055-9a29-46a1-91bf-58a8514f0825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>637d71cb-5929-4ebf-bc6e-6a717ac82bf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Sign upThis password is not safe. Please, create another.min. 8 characters, can&quot; , &quot;'&quot; , &quot;t match email or username, can&quot; , &quot;'&quot; , &quot;t be numericSign upAlready have an account? Log in.You can use social accounts to sign upContinue with FacebookContinue with TwitterContinue with SteamBy signing up, you agree to RAWG’s Terms of Service and Privacy Policy.&quot;) or . = concat(&quot;Sign upThis password is not safe. Please, create another.min. 8 characters, can&quot; , &quot;'&quot; , &quot;t match email or username, can&quot; , &quot;'&quot; , &quot;t be numericSign upAlready have an account? Log in.You can use social accounts to sign upContinue with FacebookContinue with TwitterContinue with SteamBy signing up, you agree to RAWG’s Terms of Service and Privacy Policy.&quot;))]</value>
      <webElementGuid>12394345-5ef5-4e51-b014-81c065a86961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
